# 3nity Media - Makefile
# Usage: make [target]

# Configuration
LAZBUILD := lazbuild
SRC_DIR := src
TEST_DIR := tests
TEST_RUNNER := $(TEST_DIR)/TestRunner
TEST_PROJECT := $(TEST_DIR)/TestRunner.lpi
MAIN_PROJECT := $(SRC_DIR)/TrinityMedia.lpi
RESULTS_DIR := $(TEST_DIR)/results
TESTDATA_DIR := $(TEST_DIR)/TestData
BIN_DIR := bin/x86_64-linux
BINARY_NAME := 3nity-media

# Version (from git or manually defined)
VERSION ?= $(shell git describe --tags --always --dirty 2>/dev/null || echo "dev")
BUILD_DATE := $(shell date -u +%Y-%m-%d)
BUILD_TIME := $(shell date -u +%H:%M:%S)
GIT_COMMIT := $(shell git rev-parse --short HEAD 2>/dev/null || echo "unknown")
GIT_BRANCH := $(shell git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")

# Generated version file
VERSION_FILE := $(SRC_DIR)/Core/uVersion.inc

# Colors for display
GREEN := \033[0;32m
RED := \033[0;31m
YELLOW := \033[0;33m
NC := \033[0m # No Color

.PHONY: all build build-app build-release build-tests test test-unit test-integration test-functional \
        test-performance test-robustness clean clean-all clean-backups clean-testdata clean-dist \
        generate-testdata help report coverage quick run rebuild watch ci test-verbose check-testdata \
        test-mpv test-playlist test-visual test-config test-radio \
        version version-file release release-all snap snap-clean

# Default target
all: build-app

# Help
help:
	@echo "$(GREEN)3nity Media - Makefile$(NC)"
	@echo ""
	@echo "$(YELLOW)Build:$(NC)"
	@echo "  make                - Build the application (default)"
	@echo "  make build-app      - Build the main application (Debug)"
	@echo "  make build-release  - Build in Release mode (optimized)"
	@echo "  make build-tests    - Build the TestRunner"
	@echo "  make build          - Build app + tests"
	@echo "  make run            - Build and run the application"
	@echo "  make rebuild        - Clean and rebuild everything"
	@echo "  make clean          - Clean tests"
	@echo "  make clean-all      - Clean everything (app + tests + results)"
	@echo "  make clean-backups  - Remove backup folders"
	@echo "  make clean-testdata - Remove generated test files"
	@echo "  make clean-dist     - Full cleanup before distribution"
	@echo ""
	@echo "$(YELLOW)Tests:$(NC)"
	@echo "  make test           - Run all tests"
	@echo "  make quick          - Quick tests (unit tests only)"
	@echo "  make test-unit      - Unit tests"
	@echo "  make test-integration - Integration tests"
	@echo "  make test-functional  - Functional tests (GUI)"
	@echo "  make test-performance - Performance tests"
	@echo "  make test-robustness  - Robustness tests"
	@echo ""
	@echo "$(YELLOW)Specific tests:$(NC)"
	@echo "  make test-mpv       - MPVEngine tests"
	@echo "  make test-playlist  - Playlist tests"
	@echo "  make test-visual    - Visualizations tests"
	@echo "  make test-config    - Configuration tests"
	@echo "  make test-radio     - Radio/Streaming tests"
	@echo ""
	@echo "$(YELLOW)Reports:$(NC)"
	@echo "  make report         - Generate HTML report"
	@echo "  make coverage       - Coverage report"
	@echo ""
	@echo "$(YELLOW)Test data:$(NC)"
	@echo "  make generate-testdata - Generate test files"
	@echo "  make check-testdata    - Check test files"
	@echo ""
	@echo "$(YELLOW)Development:$(NC)"
	@echo "  make watch          - Auto-rerun tests on changes"
	@echo "  make ci             - Tests for CI/CD"
	@echo ""
	@echo "$(YELLOW)Version:$(NC)"
	@echo "  make version        - Show current version"
	@echo "  make version-file   - Generate uVersion.inc file"
	@echo "  make release V=x.y.z - Build a release with version"
	@echo ""
	@echo "$(YELLOW)Snap:$(NC)"
	@echo "  make snap           - Build Snap package (with LXD)"
	@echo "  make snap-clean     - Clean Snap environment"

# === VERSION ===

# Show version
version:
	@echo "$(GREEN)3nity Media - Version information$(NC)"
	@echo "  Version:    $(VERSION)"
	@echo "  Date:       $(BUILD_DATE)"
	@echo "  Time:       $(BUILD_TIME)"
	@echo "  Commit:     $(GIT_COMMIT)"
	@echo "  Branch:     $(GIT_BRANCH)"

# Generate uVersion.inc file
version-file:
	@echo "$(GREEN)Generating $(VERSION_FILE)...$(NC)"
	@mkdir -p $(dir $(VERSION_FILE))
	@echo "{ Auto-generated by Makefile - DO NOT EDIT }" > $(VERSION_FILE)
	@echo "{ Generated: $(BUILD_DATE) $(BUILD_TIME) }" >> $(VERSION_FILE)
	@echo "" >> $(VERSION_FILE)
	@echo "const" >> $(VERSION_FILE)
	@echo "  APP_VERSION = '$(VERSION)';" >> $(VERSION_FILE)
	@echo "  APP_BUILD_DATE = '$(BUILD_DATE)';" >> $(VERSION_FILE)
	@echo "  APP_BUILD_TIME = '$(BUILD_TIME)';" >> $(VERSION_FILE)
	@echo "  APP_GIT_COMMIT = '$(GIT_COMMIT)';" >> $(VERSION_FILE)
	@echo "  APP_GIT_BRANCH = '$(GIT_BRANCH)';" >> $(VERSION_FILE)
	@echo "$(GREEN)File generated: $(VERSION_FILE)$(NC)"

# === BUILD ===

# Build with version injection (Debug mode)
build-app: version-file
	@echo "$(GREEN)Building 3nity Media $(VERSION) (Debug)...$(NC)"
	@$(LAZBUILD) $(MAIN_PROJECT)
	@echo "$(GREEN)Build complete.$(NC)"

# Build in Release mode (optimized, no debug)
build-release: version-file
	@echo "$(GREEN)Building 3nity Media $(VERSION) (Release)...$(NC)"
	@$(LAZBUILD) --build-mode=Release $(MAIN_PROJECT)
	@echo "$(GREEN)Build complete.$(NC)"

# Build tests
build-tests:
	@echo "$(GREEN)Building TestRunner...$(NC)"
	@$(LAZBUILD) $(TEST_PROJECT)
	@echo "$(GREEN)Build complete.$(NC)"

# Full build
build: build-app build-tests

# === CLEANUP ===

# Clean tests
clean:
	@echo "$(YELLOW)Cleaning tests...$(NC)"
	@rm -f $(TEST_RUNNER) $(TEST_DIR)/*.o $(TEST_DIR)/*.res
	@rm -rf $(RESULTS_DIR)
	@rm -f $(TEST_DIR)/*.xml $(TEST_DIR)/*.html
	@find $(TEST_DIR) -name "*.ppu" -delete 2>/dev/null || true
	@find $(TEST_DIR) -name "*.o" -delete 2>/dev/null || true
	@echo "$(GREEN)Cleanup complete.$(NC)"

# Full cleanup
clean-all: clean
	@echo "$(YELLOW)Full cleanup...$(NC)"
	@rm -f $(BIN_DIR)/$(BINARY_NAME)
	@rm -f $(SRC_DIR)/*.o $(SRC_DIR)/*.res
	@find $(SRC_DIR) -name "*.ppu" -delete 2>/dev/null || true
	@find $(SRC_DIR) -name "*.o" -delete 2>/dev/null || true
	@find lib -name "*.ppu" -delete 2>/dev/null || true
	@find lib -name "*.o" -delete 2>/dev/null || true
	@echo "$(GREEN)Full cleanup complete.$(NC)"

# Remove backup folders
clean-backups:
	@echo "$(YELLOW)Removing backup folders...$(NC)"
	@rm -rf $(SRC_DIR)/backup/
	@rm -rf $(SRC_DIR)/Common/backup/
	@rm -rf $(SRC_DIR)/Locale/backup/
	@rm -rf $(SRC_DIR)/Forms/backup/
	@echo "$(GREEN)Backup folders removed.$(NC)"

# Remove generated test files
clean-testdata:
	@echo "$(YELLOW)Removing generated test files...$(NC)"
	@rm -f $(TESTDATA_DIR)/audio/*.mp3 $(TESTDATA_DIR)/audio/*.ogg $(TESTDATA_DIR)/audio/*.flac
	@rm -f $(TESTDATA_DIR)/audio/*.wav $(TESTDATA_DIR)/audio/*.m4a $(TESTDATA_DIR)/audio/*.opus
	@rm -f $(TESTDATA_DIR)/video/*.mp4 $(TESTDATA_DIR)/video/*.mkv $(TESTDATA_DIR)/video/*.webm
	@rm -f $(TESTDATA_DIR)/video/*.avi
	@echo "$(GREEN)Test files removed.$(NC)"

# Full cleanup before distribution (GitHub)
clean-dist: clean-all clean-backups clean-testdata
	@echo "$(YELLOW)Cleanup for distribution...$(NC)"
	@rm -rf bin/ lib/ tests/bin/ tests/lib/
	@rm -f $(SRC_DIR)/TrinityMedia.lps
	@echo "$(GREEN)Project ready for distribution.$(NC)"
	@echo ""
	@echo "Project size:"
	@du -sh .

# Create results folder
$(RESULTS_DIR):
	@mkdir -p $(RESULTS_DIR)

# === TESTS ===

# All tests
test: build-tests $(RESULTS_DIR)
	@echo "$(GREEN)Running all tests...$(NC)"
	@$(TEST_RUNNER) --all --format=xml --output=$(RESULTS_DIR)/all-results.xml
	@echo "$(GREEN)Tests complete. Results: $(RESULTS_DIR)/all-results.xml$(NC)"

# Quick tests (unit tests only, no external dependencies)
quick: build-tests $(RESULTS_DIR)
	@echo "$(GREEN)Quick tests (unit tests)...$(NC)"
	@$(TEST_RUNNER) --suite=Unit --format=xml --output=$(RESULTS_DIR)/quick-results.xml

# Unit tests
test-unit: build-tests $(RESULTS_DIR)
	@echo "$(GREEN)Unit tests...$(NC)"
	@$(TEST_RUNNER) --suite=Unit --format=xml --output=$(RESULTS_DIR)/unit-results.xml

# Integration tests
test-integration: build-tests $(RESULTS_DIR)
	@echo "$(GREEN)Integration tests...$(NC)"
	@$(TEST_RUNNER) --suite=Integration --format=xml --output=$(RESULTS_DIR)/integration-results.xml

# Functional tests (GUI)
test-functional: build-tests $(RESULTS_DIR)
	@echo "$(GREEN)Functional tests (GUI)...$(NC)"
	@$(TEST_RUNNER) --suite=Functional --format=xml --output=$(RESULTS_DIR)/functional-results.xml

# Performance tests
test-performance: build-tests $(RESULTS_DIR)
	@echo "$(GREEN)Performance tests...$(NC)"
	@$(TEST_RUNNER) --suite=Performance --format=xml --output=$(RESULTS_DIR)/performance-results.xml

# Robustness tests
test-robustness: build-tests $(RESULTS_DIR)
	@echo "$(GREEN)Robustness tests...$(NC)"
	@$(TEST_RUNNER) --suite=Robustness --format=xml --output=$(RESULTS_DIR)/robustness-results.xml

# === SPECIFIC TESTS ===

test-mpv: build-tests $(RESULTS_DIR)
	@echo "$(GREEN)MPVEngine tests...$(NC)"
	@$(TEST_RUNNER) --suite=TTestLibMPV --suite=TTestMPVEngine --format=xml --output=$(RESULTS_DIR)/mpv-results.xml

test-playlist: build-tests $(RESULTS_DIR)
	@echo "$(GREEN)Playlist tests...$(NC)"
	@$(TEST_RUNNER) --suite=TTestPlaylist --format=xml --output=$(RESULTS_DIR)/playlist-results.xml

test-visual: build-tests $(RESULTS_DIR)
	@echo "$(GREEN)Visualizations tests...$(NC)"
	@$(TEST_RUNNER) --suite=TTestVisualEffects --format=xml --output=$(RESULTS_DIR)/visual-results.xml

test-config: build-tests $(RESULTS_DIR)
	@echo "$(GREEN)Configuration tests...$(NC)"
	@$(TEST_RUNNER) --suite=TTestConfig --format=xml --output=$(RESULTS_DIR)/config-results.xml

test-radio: build-tests $(RESULTS_DIR)
	@echo "$(GREEN)Radio/Streaming tests...$(NC)"
	@$(TEST_RUNNER) --suite=TTestRadioManager --suite=TTestStreaming --format=xml --output=$(RESULTS_DIR)/radio-results.xml

# === REPORTS ===

report: build-tests $(RESULTS_DIR)
	@echo "$(GREEN)Generating HTML report...$(NC)"
	@$(TEST_RUNNER) --all --format=html --output=$(RESULTS_DIR)/report.html
	@echo "$(GREEN)Report generated: $(RESULTS_DIR)/report.html$(NC)"

coverage: build-tests $(RESULTS_DIR)
	@echo "$(GREEN)Generating coverage report...$(NC)"
	@$(TEST_RUNNER) --all --coverage --format=html --output=$(RESULTS_DIR)/coverage.html
	@echo "$(GREEN)Coverage report: $(RESULTS_DIR)/coverage.html$(NC)"

# === TEST DATA ===

generate-testdata:
	@echo "$(GREEN)Generating test files...$(NC)"
	@chmod +x $(TEST_DIR)/generate_test_files.sh
	@cd $(TEST_DIR) && ./generate_test_files.sh
	@echo "$(GREEN)Test files generated.$(NC)"

check-testdata:
	@echo "$(YELLOW)Checking test files...$(NC)"
	@echo ""
	@echo "Audio:"
	@ls -la $(TESTDATA_DIR)/audio/ 2>/dev/null || echo "  $(RED)Audio folder missing$(NC)"
	@echo ""
	@echo "Video:"
	@ls -la $(TESTDATA_DIR)/video/ 2>/dev/null || echo "  $(RED)Video folder missing$(NC)"
	@echo ""
	@echo "Subtitles:"
	@ls -la $(TESTDATA_DIR)/subtitles/ 2>/dev/null || echo "  $(RED)Subtitles folder missing$(NC)"
	@echo ""
	@echo "Playlists:"
	@ls -la $(TESTDATA_DIR)/playlists/ 2>/dev/null || echo "  $(RED)Playlists folder missing$(NC)"

# === VERBOSE MODE ===

test-verbose: build-tests
	@echo "$(GREEN)Tests in verbose mode...$(NC)"
	@$(TEST_RUNNER) --all --verbose

# === CI/CD ===

ci: build-tests $(RESULTS_DIR)
	@echo "$(GREEN)Running CI...$(NC)"
	@$(TEST_RUNNER) --suite=Unit --format=xml --output=$(RESULTS_DIR)/ci-unit.xml
	@$(TEST_RUNNER) --suite=Integration --format=xml --output=$(RESULTS_DIR)/ci-integration.xml
	@echo "$(GREEN)CI complete.$(NC)"

# === WATCH MODE (requires inotify-tools) ===

watch:
	@echo "$(GREEN)Watch mode enabled. Ctrl+C to stop.$(NC)"
	@while true; do \
		inotifywait -q -e modify -r $(SRC_DIR)/; \
		echo "$(YELLOW)Change detected, rerunning tests...$(NC)"; \
		make quick; \
	done

# === SHORTCUTS ===

# Build and run
run: build-app
	@echo "$(GREEN)Launching 3nity Media...$(NC)"
	@$(BIN_DIR)/$(BINARY_NAME)

# Full rebuild
rebuild: clean-all build

# === RELEASES ===

# Release with specific version
# Usage: make release V=1.0.0
release:
ifndef V
	$(error Version required. Usage: make release V=1.0.0)
endif
	@echo "$(GREEN)Creating release $(V)...$(NC)"
	$(MAKE) VERSION=$(V) clean-all build-release
	@mkdir -p releases
	@cp $(BIN_DIR)/$(BINARY_NAME) releases/3nity-$(V)-linux-x64
	@echo "$(GREEN)Release created: releases/3nity-$(V)-linux-x64$(NC)"

# Release for all platforms (if cross-compilation configured)
release-all:
ifndef V
	$(error Version required. Usage: make release-all V=1.0.0)
endif
	@echo "$(GREEN)Creating releases $(V) for all platforms...$(NC)"
	@mkdir -p releases
	# Linux x64
	$(MAKE) VERSION=$(V) build-release
	@cp $(BIN_DIR)/$(BINARY_NAME) releases/3nity-$(V)-linux-x64
	# Add other platforms here if cross-compilation available
	@echo "$(GREEN)Releases created in releases/$(NC)"
	@ls -la releases/

# === SNAP ===

# Build Snap package (with LXD)
snap: build-release
	@echo "$(GREEN)=== Building Snap package ===$(NC)"
	@# Save iptables FORWARD state and enable if necessary
	@FORWARD_POLICY=$$(sudo iptables -L FORWARD 2>/dev/null | head -1 | grep -oP '(?<=policy )\w+' || echo "ACCEPT"); \
	if [ "$$FORWARD_POLICY" = "DROP" ]; then \
		echo "$(YELLOW)Enabling iptables FORWARD for LXD...$(NC)"; \
		sudo iptables -P FORWARD ACCEPT; \
		RESTORE_IPTABLES=1; \
	else \
		RESTORE_IPTABLES=0; \
	fi; \
	\
	echo "$(YELLOW)Clearing snapcraft cache...$(NC)"; \
	sudo rm -rf /root/.cache/snapcraft 2>/dev/null || true; \
	rm -rf ~/.cache/snapcraft 2>/dev/null || true; \
	\
	echo "$(YELLOW)Removing LXD instance...$(NC)"; \
	lxc delete snapcraft-3nity-media --force 2>/dev/null || true; \
	\
	echo "$(YELLOW)Cleaning snapcraft...$(NC)"; \
	snapcraft clean 2>/dev/null || true; \
	\
	echo "$(GREEN)Building snap...$(NC)"; \
	snapcraft; \
	BUILD_STATUS=$$?; \
	\
	if [ "$$RESTORE_IPTABLES" = "1" ]; then \
		echo "$(YELLOW)Restoring iptables FORWARD to DROP...$(NC)"; \
		sudo iptables -P FORWARD DROP; \
	fi; \
	\
	if [ $$BUILD_STATUS -eq 0 ]; then \
		echo "$(GREEN)=== Snap package created successfully ===$(NC)"; \
		ls -la *.snap 2>/dev/null || true; \
	else \
		echo "$(RED)=== Snap build failed ===$(NC)"; \
		exit 1; \
	fi

# Clean Snap environment
snap-clean:
	@echo "$(YELLOW)Cleaning Snap environment...$(NC)"
	@sudo rm -rf /root/.cache/snapcraft 2>/dev/null || true
	@rm -rf ~/.cache/snapcraft 2>/dev/null || true
	@lxc delete snapcraft-3nity-media --force 2>/dev/null || true
	@snapcraft clean 2>/dev/null || true
	@rm -f *.snap 2>/dev/null || true
	@echo "$(GREEN)Snap environment cleaned.$(NC)"
