# 3nity Media - Makefile
# Usage: make [target]

# Configuration
LAZBUILD := lazbuild
SRC_DIR := src
TEST_DIR := tests
TEST_RUNNER := $(TEST_DIR)/TestRunner
TEST_PROJECT := $(TEST_DIR)/TestRunner.lpi
MAIN_PROJECT := $(SRC_DIR)/TrinityMedia.lpi
RESULTS_DIR := $(TEST_DIR)/results
TESTDATA_DIR := $(TEST_DIR)/TestData
BIN_DIR := bin/x86_64-linux
BINARY_NAME := 3nity-media

# Version (depuis git ou définie manuellement)
VERSION ?= $(shell git describe --tags --always --dirty 2>/dev/null || echo "dev")
BUILD_DATE := $(shell date -u +%Y-%m-%d)
BUILD_TIME := $(shell date -u +%H:%M:%S)
GIT_COMMIT := $(shell git rev-parse --short HEAD 2>/dev/null || echo "unknown")
GIT_BRANCH := $(shell git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")

# Fichier version généré
VERSION_FILE := $(SRC_DIR)/Core/uVersion.inc

# Couleurs pour l'affichage
GREEN := \033[0;32m
RED := \033[0;31m
YELLOW := \033[0;33m
NC := \033[0m # No Color

.PHONY: all build build-app build-release build-tests test test-unit test-integration test-functional \
        test-performance test-robustness clean clean-all clean-backups clean-testdata clean-dist \
        generate-testdata help report coverage quick run rebuild watch ci test-verbose check-testdata \
        test-mpv test-playlist test-visual test-config test-radio \
        version version-file release release-all

# Cible par défaut
all: build-app

# Aide
help:
	@echo "$(GREEN)3nity Media - Makefile$(NC)"
	@echo ""
	@echo "$(YELLOW)Compilation:$(NC)"
	@echo "  make                - Compiler l'application (par défaut)"
	@echo "  make build-app      - Compiler l'application principale (Debug)"
	@echo "  make build-release  - Compiler en mode Release (optimisé)"
	@echo "  make build-tests    - Compiler le TestRunner"
	@echo "  make build          - Compiler app + tests"
	@echo "  make run            - Compiler et lancer l'application"
	@echo "  make rebuild        - Nettoyer et recompiler tout"
	@echo "  make clean          - Nettoyer les tests"
	@echo "  make clean-all      - Nettoyer tout (app + tests + résultats)"
	@echo "  make clean-backups  - Supprimer les dossiers backup"
	@echo "  make clean-testdata - Supprimer les fichiers de test générés"
	@echo "  make clean-dist     - Nettoyage complet avant distribution"
	@echo ""
	@echo "$(YELLOW)Tests:$(NC)"
	@echo "  make test           - Exécuter tous les tests"
	@echo "  make quick          - Tests rapides (unitaires uniquement)"
	@echo "  make test-unit      - Tests unitaires"
	@echo "  make test-integration - Tests d'intégration"
	@echo "  make test-functional  - Tests fonctionnels (GUI)"
	@echo "  make test-performance - Tests de performance"
	@echo "  make test-robustness  - Tests de robustesse"
	@echo ""
	@echo "$(YELLOW)Tests spécifiques:$(NC)"
	@echo "  make test-mpv       - Tests MPVEngine"
	@echo "  make test-playlist  - Tests Playlist"
	@echo "  make test-visual    - Tests Visualisations"
	@echo "  make test-config    - Tests Configuration"
	@echo "  make test-radio     - Tests Radio/Streaming"
	@echo ""
	@echo "$(YELLOW)Rapports:$(NC)"
	@echo "  make report         - Générer rapport HTML"
	@echo "  make coverage       - Rapport de couverture"
	@echo ""
	@echo "$(YELLOW)Données de test:$(NC)"
	@echo "  make generate-testdata - Générer les fichiers de test"
	@echo "  make check-testdata    - Vérifier les fichiers de test"
	@echo ""
	@echo "$(YELLOW)Développement:$(NC)"
	@echo "  make watch          - Relancer tests auto à chaque modif"
	@echo "  make ci             - Tests pour CI/CD"
	@echo ""
	@echo "$(YELLOW)Version:$(NC)"
	@echo "  make version        - Afficher la version actuelle"
	@echo "  make version-file   - Générer le fichier uVersion.inc"
	@echo "  make release V=x.y.z - Compiler une release avec version"

# === VERSION ===

# Afficher la version
version:
	@echo "$(GREEN)3nity Media - Informations de version$(NC)"
	@echo "  Version:    $(VERSION)"
	@echo "  Date:       $(BUILD_DATE)"
	@echo "  Heure:      $(BUILD_TIME)"
	@echo "  Commit:     $(GIT_COMMIT)"
	@echo "  Branche:    $(GIT_BRANCH)"

# Générer le fichier uVersion.inc
version-file:
	@echo "$(GREEN)Génération de $(VERSION_FILE)...$(NC)"
	@mkdir -p $(dir $(VERSION_FILE))
	@echo "{ Auto-generated by Makefile - DO NOT EDIT }" > $(VERSION_FILE)
	@echo "{ Generated: $(BUILD_DATE) $(BUILD_TIME) }" >> $(VERSION_FILE)
	@echo "" >> $(VERSION_FILE)
	@echo "const" >> $(VERSION_FILE)
	@echo "  APP_VERSION = '$(VERSION)';" >> $(VERSION_FILE)
	@echo "  APP_BUILD_DATE = '$(BUILD_DATE)';" >> $(VERSION_FILE)
	@echo "  APP_BUILD_TIME = '$(BUILD_TIME)';" >> $(VERSION_FILE)
	@echo "  APP_GIT_COMMIT = '$(GIT_COMMIT)';" >> $(VERSION_FILE)
	@echo "  APP_GIT_BRANCH = '$(GIT_BRANCH)';" >> $(VERSION_FILE)
	@echo "$(GREEN)Fichier généré: $(VERSION_FILE)$(NC)"

# === COMPILATION ===

# Compilation avec injection de version (mode Debug)
build-app: version-file
	@echo "$(GREEN)Compilation de 3nity Media $(VERSION) (Debug)...$(NC)"
	@$(LAZBUILD) $(MAIN_PROJECT)
	@echo "$(GREEN)Compilation terminée.$(NC)"

# Compilation en mode Release (optimisé, sans debug)
build-release: version-file
	@echo "$(GREEN)Compilation de 3nity Media $(VERSION) (Release)...$(NC)"
	@$(LAZBUILD) --build-mode=Release $(MAIN_PROJECT)
	@echo "$(GREEN)Compilation terminée.$(NC)"

# Compilation tests
build-tests:
	@echo "$(GREEN)Compilation du TestRunner...$(NC)"
	@$(LAZBUILD) $(TEST_PROJECT)
	@echo "$(GREEN)Compilation terminée.$(NC)"

# Compilation complète
build: build-app build-tests

# === NETTOYAGE ===

# Nettoyage tests
clean:
	@echo "$(YELLOW)Nettoyage des tests...$(NC)"
	@rm -f $(TEST_RUNNER) $(TEST_DIR)/*.o $(TEST_DIR)/*.res
	@rm -rf $(RESULTS_DIR)
	@rm -f $(TEST_DIR)/*.xml $(TEST_DIR)/*.html
	@find $(TEST_DIR) -name "*.ppu" -delete 2>/dev/null || true
	@find $(TEST_DIR) -name "*.o" -delete 2>/dev/null || true
	@echo "$(GREEN)Nettoyage terminé.$(NC)"

# Nettoyage complet
clean-all: clean
	@echo "$(YELLOW)Nettoyage complet...$(NC)"
	@rm -f $(BIN_DIR)/$(BINARY_NAME)
	@rm -f $(SRC_DIR)/*.o $(SRC_DIR)/*.res
	@find $(SRC_DIR) -name "*.ppu" -delete 2>/dev/null || true
	@find $(SRC_DIR) -name "*.o" -delete 2>/dev/null || true
	@find lib -name "*.ppu" -delete 2>/dev/null || true
	@find lib -name "*.o" -delete 2>/dev/null || true
	@echo "$(GREEN)Nettoyage complet terminé.$(NC)"

# Supprimer les dossiers backup
clean-backups:
	@echo "$(YELLOW)Suppression des dossiers backup...$(NC)"
	@rm -rf $(SRC_DIR)/backup/
	@rm -rf $(SRC_DIR)/Common/backup/
	@rm -rf $(SRC_DIR)/Locale/backup/
	@rm -rf $(SRC_DIR)/Forms/backup/
	@echo "$(GREEN)Dossiers backup supprimés.$(NC)"

# Supprimer les fichiers de test générés
clean-testdata:
	@echo "$(YELLOW)Suppression des fichiers de test générés...$(NC)"
	@rm -f $(TESTDATA_DIR)/audio/*.mp3 $(TESTDATA_DIR)/audio/*.ogg $(TESTDATA_DIR)/audio/*.flac
	@rm -f $(TESTDATA_DIR)/audio/*.wav $(TESTDATA_DIR)/audio/*.m4a $(TESTDATA_DIR)/audio/*.opus
	@rm -f $(TESTDATA_DIR)/video/*.mp4 $(TESTDATA_DIR)/video/*.mkv $(TESTDATA_DIR)/video/*.webm
	@rm -f $(TESTDATA_DIR)/video/*.avi
	@echo "$(GREEN)Fichiers de test supprimés.$(NC)"

# Nettoyage complet avant distribution (GitHub)
clean-dist: clean-all clean-backups clean-testdata
	@echo "$(YELLOW)Nettoyage pour distribution...$(NC)"
	@rm -rf bin/ lib/ tests/bin/ tests/lib/
	@rm -f $(SRC_DIR)/TrinityMedia.lps
	@echo "$(GREEN)Projet prêt pour distribution.$(NC)"
	@echo ""
	@echo "Taille du projet:"
	@du -sh .

# Créer le dossier de résultats
$(RESULTS_DIR):
	@mkdir -p $(RESULTS_DIR)

# === TESTS ===

# Tous les tests
test: build-tests $(RESULTS_DIR)
	@echo "$(GREEN)Exécution de tous les tests...$(NC)"
	@$(TEST_RUNNER) --all --format=xml --output=$(RESULTS_DIR)/all-results.xml
	@echo "$(GREEN)Tests terminés. Résultats: $(RESULTS_DIR)/all-results.xml$(NC)"

# Tests rapides (unitaires seulement, sans dépendances externes)
quick: build-tests $(RESULTS_DIR)
	@echo "$(GREEN)Tests rapides (unitaires)...$(NC)"
	@$(TEST_RUNNER) --suite=Unit --format=xml --output=$(RESULTS_DIR)/quick-results.xml

# Tests unitaires
test-unit: build-tests $(RESULTS_DIR)
	@echo "$(GREEN)Tests unitaires...$(NC)"
	@$(TEST_RUNNER) --suite=Unit --format=xml --output=$(RESULTS_DIR)/unit-results.xml

# Tests d'intégration
test-integration: build-tests $(RESULTS_DIR)
	@echo "$(GREEN)Tests d'intégration...$(NC)"
	@$(TEST_RUNNER) --suite=Integration --format=xml --output=$(RESULTS_DIR)/integration-results.xml

# Tests fonctionnels (GUI)
test-functional: build-tests $(RESULTS_DIR)
	@echo "$(GREEN)Tests fonctionnels (GUI)...$(NC)"
	@$(TEST_RUNNER) --suite=Functional --format=xml --output=$(RESULTS_DIR)/functional-results.xml

# Tests de performance
test-performance: build-tests $(RESULTS_DIR)
	@echo "$(GREEN)Tests de performance...$(NC)"
	@$(TEST_RUNNER) --suite=Performance --format=xml --output=$(RESULTS_DIR)/performance-results.xml

# Tests de robustesse
test-robustness: build-tests $(RESULTS_DIR)
	@echo "$(GREEN)Tests de robustesse...$(NC)"
	@$(TEST_RUNNER) --suite=Robustness --format=xml --output=$(RESULTS_DIR)/robustness-results.xml

# === TESTS SPÉCIFIQUES ===

test-mpv: build-tests $(RESULTS_DIR)
	@echo "$(GREEN)Tests MPVEngine...$(NC)"
	@$(TEST_RUNNER) --suite=TTestLibMPV --suite=TTestMPVEngine --format=xml --output=$(RESULTS_DIR)/mpv-results.xml

test-playlist: build-tests $(RESULTS_DIR)
	@echo "$(GREEN)Tests Playlist...$(NC)"
	@$(TEST_RUNNER) --suite=TTestPlaylist --format=xml --output=$(RESULTS_DIR)/playlist-results.xml

test-visual: build-tests $(RESULTS_DIR)
	@echo "$(GREEN)Tests Visualisations...$(NC)"
	@$(TEST_RUNNER) --suite=TTestVisualEffects --format=xml --output=$(RESULTS_DIR)/visual-results.xml

test-config: build-tests $(RESULTS_DIR)
	@echo "$(GREEN)Tests Configuration...$(NC)"
	@$(TEST_RUNNER) --suite=TTestConfig --format=xml --output=$(RESULTS_DIR)/config-results.xml

test-radio: build-tests $(RESULTS_DIR)
	@echo "$(GREEN)Tests Radio/Streaming...$(NC)"
	@$(TEST_RUNNER) --suite=TTestRadioManager --suite=TTestStreaming --format=xml --output=$(RESULTS_DIR)/radio-results.xml

# === RAPPORTS ===

report: build-tests $(RESULTS_DIR)
	@echo "$(GREEN)Génération du rapport HTML...$(NC)"
	@$(TEST_RUNNER) --all --format=html --output=$(RESULTS_DIR)/report.html
	@echo "$(GREEN)Rapport généré: $(RESULTS_DIR)/report.html$(NC)"

coverage: build-tests $(RESULTS_DIR)
	@echo "$(GREEN)Génération du rapport de couverture...$(NC)"
	@$(TEST_RUNNER) --all --coverage --format=html --output=$(RESULTS_DIR)/coverage.html
	@echo "$(GREEN)Rapport de couverture: $(RESULTS_DIR)/coverage.html$(NC)"

# === DONNÉES DE TEST ===

generate-testdata:
	@echo "$(GREEN)Génération des fichiers de test...$(NC)"
	@chmod +x $(TEST_DIR)/generate_test_files.sh
	@cd $(TEST_DIR) && ./generate_test_files.sh
	@echo "$(GREEN)Fichiers de test générés.$(NC)"

check-testdata:
	@echo "$(YELLOW)Vérification des fichiers de test...$(NC)"
	@echo ""
	@echo "Audio:"
	@ls -la $(TESTDATA_DIR)/audio/ 2>/dev/null || echo "  $(RED)Dossier audio manquant$(NC)"
	@echo ""
	@echo "Video:"
	@ls -la $(TESTDATA_DIR)/video/ 2>/dev/null || echo "  $(RED)Dossier video manquant$(NC)"
	@echo ""
	@echo "Subtitles:"
	@ls -la $(TESTDATA_DIR)/subtitles/ 2>/dev/null || echo "  $(RED)Dossier subtitles manquant$(NC)"
	@echo ""
	@echo "Playlists:"
	@ls -la $(TESTDATA_DIR)/playlists/ 2>/dev/null || echo "  $(RED)Dossier playlists manquant$(NC)"

# === MODE VERBOSE ===

test-verbose: build-tests
	@echo "$(GREEN)Tests en mode verbose...$(NC)"
	@$(TEST_RUNNER) --all --verbose

# === CI/CD ===

ci: build-tests $(RESULTS_DIR)
	@echo "$(GREEN)Exécution CI...$(NC)"
	@$(TEST_RUNNER) --suite=Unit --format=xml --output=$(RESULTS_DIR)/ci-unit.xml
	@$(TEST_RUNNER) --suite=Integration --format=xml --output=$(RESULTS_DIR)/ci-integration.xml
	@echo "$(GREEN)CI terminée.$(NC)"

# === WATCH MODE (nécessite inotify-tools) ===

watch:
	@echo "$(GREEN)Mode watch activé. Ctrl+C pour arrêter.$(NC)"
	@while true; do \
		inotifywait -q -e modify -r $(SRC_DIR)/; \
		echo "$(YELLOW)Changement détecté, relancement des tests...$(NC)"; \
		make quick; \
	done

# === RACCOURCIS ===

# Compiler et lancer
run: build-app
	@echo "$(GREEN)Lancement de 3nity Media...$(NC)"
	@$(BIN_DIR)/$(BINARY_NAME)

# Rebuild complet
rebuild: clean-all build

# === RELEASES ===

# Release avec version spécifique
# Usage: make release V=1.0.0
release:
ifndef V
	$(error Version requise. Usage: make release V=1.0.0)
endif
	@echo "$(GREEN)Création de la release $(V)...$(NC)"
	$(MAKE) VERSION=$(V) clean-all build-release
	@mkdir -p releases
	@cp $(BIN_DIR)/$(BINARY_NAME) releases/3nity-$(V)-linux-x64
	@echo "$(GREEN)Release créée: releases/3nity-$(V)-linux-x64$(NC)"

# Release pour toutes les plateformes (si cross-compilation configurée)
release-all:
ifndef V
	$(error Version requise. Usage: make release-all V=1.0.0)
endif
	@echo "$(GREEN)Création des releases $(V) pour toutes les plateformes...$(NC)"
	@mkdir -p releases
	# Linux x64
	$(MAKE) VERSION=$(V) build-release
	@cp $(BIN_DIR)/$(BINARY_NAME) releases/3nity-$(V)-linux-x64
	# Ajouter ici d'autres plateformes si cross-compilation disponible
	@echo "$(GREEN)Releases créées dans releases/$(NC)"
	@ls -la releases/
