{ ===============================================================================
  uAppVersion.pas - Application Version Information

  Part of 3nity Media - Lazarus Edition

  This unit provides version information that is automatically generated
  by the Makefile from git tags and commit information.

  Usage:
    - Run 'make build-app' to generate uVersion.inc before compilation
    - Or run 'make version-file' to generate it manually

  The uVersion.inc file contains:
    APP_VERSION     - Version string from git describe (e.g., 'v1.2.3')
    APP_BUILD_DATE  - Build date (YYYY-MM-DD)
    APP_BUILD_TIME  - Build time (HH:MM:SS)
    APP_GIT_COMMIT  - Short git commit hash
    APP_GIT_BRANCH  - Current git branch name

  Author: Nicolas DEOUX (NDXDev@gmail.com)
  License: GPL-2.0
  =============================================================================== }

unit uAppVersion;

{$mode objfpc}{$H+}
{$WARN 6018 OFF} // Unreachable code: intentional for git/non-git builds

interface

{ Include version file generated by Makefile }
{ If uVersion.inc doesn't exist, create it with: make version-file }
{$I uVersion.inc}

{ Version functions }
function GetAppName: string;
function GetAppVersion: string;
function GetAppVersionShort: string;
function GetAppFullVersion: string;
function GetBuildDate: string;
function GetBuildTime: string;
function GetBuildDateTime: string;
function GetGitCommit: string;
function GetGitBranch: string;
function GetBuildInfo: string;
function GetFullVersionInfo: string;
function GetVersionForTitle: string;
function GetVersionForAbout: string;

implementation

uses
  SysUtils, uConstants;

function GetAppName: string;
begin
  Result := APP_NAME;
end;

function GetAppVersion: string;
begin
  Result := APP_VERSION;
end;

function GetAppVersionShort: string;
begin
  { Remove 'v' prefix if present }
  if (Length(APP_VERSION) > 0) and (APP_VERSION[1] = 'v') then
    Result := Copy(APP_VERSION, 2, Length(APP_VERSION) - 1)
  else
    Result := APP_VERSION;
end;

function GetAppFullVersion: string;
begin
  Result := Format('%s %s', [APP_NAME, APP_VERSION]);
end;

function GetBuildDate: string;
begin
  Result := APP_BUILD_DATE;
end;

function GetBuildTime: string;
begin
  Result := APP_BUILD_TIME;
end;

function GetBuildDateTime: string;
begin
  Result := Format('%s %s', [APP_BUILD_DATE, APP_BUILD_TIME]);
end;

function GetGitCommit: string;
begin
  Result := APP_GIT_COMMIT;
end;

function GetGitBranch: string;
begin
  Result := APP_GIT_BRANCH;
end;

function GetBuildInfo: string;
begin
  if APP_GIT_COMMIT = 'unknown' then
    Result := Format('Built: %s %s', [APP_BUILD_DATE, APP_BUILD_TIME])
  else
    Result := Format('Built: %s %s | Commit: %s (%s)',
      [APP_BUILD_DATE, APP_BUILD_TIME, APP_GIT_COMMIT, APP_GIT_BRANCH]);
end;

function GetFullVersionInfo: string;
begin
  if APP_GIT_COMMIT = 'unknown' then
    Result := APP_VERSION
  else
    Result := Format('%s (%s)', [APP_VERSION, APP_GIT_COMMIT]);
end;

function GetVersionForTitle: string;
begin
  { Format for window title: "3nity Media v1.2.3" }
  Result := Format('%s %s', [APP_NAME, APP_VERSION]);
end;

function GetVersionForAbout: string;
begin
  { Format for About dialog }
  Result := Format('%s'#13#10 +
                   'Version: %s'#13#10 +
                   'Build: %s %s'#13#10 +
                   'Commit: %s'#13#10 +
                   'Branch: %s',
    [APP_NAME, APP_VERSION, APP_BUILD_DATE, APP_BUILD_TIME,
     APP_GIT_COMMIT, APP_GIT_BRANCH]);
end;

end.
