name: 3nity-media
version: git
summary: Modern multimedia player powered by libmpv
description: |
  3nity Media is a modern, lightweight media player built with
  Lazarus/Free Pascal and powered by the libmpv engine.

  Features:
  - Audio and video playback with libmpv
  - Playlist management (M3U, PLS, XSPF)
  - Internet radio streaming
  - Audio equalizer
  - Video adjustments
  - Keyboard shortcuts
  - Multi-language support (100+ languages)

grade: stable
confinement: strict
base: core24
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]

icon: snap/gui/3nity-media.png

layout:
  /usr/share/libdrm:
    bind: $SNAP/usr/share/libdrm
  /usr/lib/x86_64-linux-gnu/dri:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/dri

apps:
  3nity-media:
    extensions: [kde-neon]
    command: usr/bin/3nity-media
    desktop: usr/share/applications/3nity-media.desktop
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib:$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu/pulseaudio:$SNAP/usr/lib/x86_64-linux-gnu/blas:$SNAP/usr/lib/x86_64-linux-gnu/lapack:$LD_LIBRARY_PATH
      UBUNTU_MENUPROXY: ""
      QT_QPA_PLATFORM: xcb
      SSL_CERT_DIR: $SNAP/etc/ssl/certs
      SSL_CERT_FILE: $SNAP/etc/ssl/certs/ca-certificates.crt
    plugs:
      - home
      - audio-playback
      - audio-record
      - pulseaudio
      - network
      - network-bind
      - opengl
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - removable-media
      - optical-drive
      - unity7
      - gsettings
      - udisks2
      - screen-inhibit-control
      - mount-observe

parts:
  3nity-media:
    plugin: nil
    source: .
    build-packages:
      - wget
    override-build: |
      # Download and install OpenSSL 1.1.x (required by FPC for HTTPS)
      wget -q http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
      dpkg-deb -x libssl1.1_1.1.1f-1ubuntu2_amd64.deb $SNAPCRAFT_PART_INSTALL/
      rm libssl1.1_1.1.1f-1ubuntu2_amd64.deb
      echo "=== OpenSSL 1.1 installed ==="
      ls -la $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/libssl* || true
      ls -la $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/libcrypto* || true

      # Copy binary
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      cp bin/x86_64-linux/3nity-media $SNAPCRAFT_PART_INSTALL/usr/bin/
      chmod +x $SNAPCRAFT_PART_INSTALL/usr/bin/3nity-media

      # Copy locale files
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/3nity-media/locale
      cp resources/locale/*.lang $SNAPCRAFT_PART_INSTALL/usr/share/3nity-media/locale/ || true

      # Copy documentation
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/doc/3nity-media
      cp LICENSE $SNAPCRAFT_PART_INSTALL/usr/share/doc/3nity-media/ || true
      cp README.md $SNAPCRAFT_PART_INSTALL/usr/share/doc/3nity-media/ || true

      # Copy desktop file
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/applications
      cp snap/gui/3nity-media.desktop $SNAPCRAFT_PART_INSTALL/usr/share/applications/

      # Copy icons
      for size in 16 24 32 48 64 128 256; do
        mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/${size}x${size}/apps
        cp snap/gui/3nity-media-${size}.png $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/${size}x${size}/apps/3nity-media.png || true
      done

      echo "=== Snap build contents ==="
      ls -la $SNAPCRAFT_PART_INSTALL/usr/bin/
    stage-packages:
      - libmpv2
      - libqt5pas1
      - ffmpeg
      - ca-certificates
      - libva2
      - libva-drm2
      - libva-x11-2
      - libvdpau1
      - mesa-va-drivers
      - mesa-vdpau-drivers
      - libdrm2
      - libdrm-common
      - libegl1
      - libgl1
      - libglx0
      - libglvnd0
      - libpulse0
      - libpulse-mainloop-glib0
      - libasound2
      - liblua5.1-0
      - libass9
      - libbluray2
      - libcdio-paranoia2
      - libdvdnav4
      - libdvdread8
      - libjpeg8
      - librubberband2
      - libsdl2-2.0-0
      - libsixel1
      - libsmbclient
      - libuchardet0
      - libxkbcommon0
      - libxss1
      - libzimg2
      - libblas3
      - liblapack3
      - plasma-integration
      - qt5-style-plugins
      - breeze-icon-theme
      - kde-style-breeze
      - gsettings-desktop-schemas

  # Cleanup to reduce snap size
  cleanup:
    after: [3nity-media]
    plugin: nil
    override-prime: |
      set -eux
      # Remove unnecessary files to reduce snap size
      rm -rf usr/share/doc
      rm -rf usr/share/man
      rm -rf usr/share/lintian
      rm -rf usr/share/bug
      rm -rf usr/lib/*/cmake
      rm -rf usr/lib/*/pkgconfig
      find . -name "*.a" -delete
      find . -name "*.la" -delete
