{ ═══════════════════════════════════════════════════════════════════════════════
  uConstants.pas - Application-wide Constants

  Part of 3nity Media - Lazarus Edition

  This unit defines application-wide constants for the UI and general
  configuration. Core/playback constants are in uMPVConst.pas.

  Author: Nicolas DEOUX (NDXDev@gmail.com)
  License: GPL-2.0
  ═══════════════════════════════════════════════════════════════════════════════ }

unit uConstants;

{$mode objfpc}{$H+}

interface

uses
  Graphics;

const
  { ═══════════════════════════════════════════════════════════════════════════
    APPLICATION INFO
    Note: APP_VERSION is defined in uVersion.inc (auto-generated by Makefile)
    ═══════════════════════════════════════════════════════════════════════════ }
  APP_NAME = '3nity Media';
  APP_COPYRIGHT = 'Copyright (c) 2025 Nicolas DEOUX';
  APP_COPYRIGHT_BASE = 'Copyright (c) 2025-';
  APP_AUTHOR = ' Nicolas DEOUX';
  APP_GITHUB = 'https://github.com/NDXDeveloper/3nity-media';
  APP_LINKEDIN = 'https://www.linkedin.com/in/nicolas-deoux-ab295980/';
  APP_TWITTER = 'https://x.com/NDXDev';
  APP_BLUESKY = 'https://bsky.app/profile/ndxdev.bsky.social';

  { ═══════════════════════════════════════════════════════════════════════════
    UI DIMENSIONS
    ═══════════════════════════════════════════════════════════════════════════ }
  DEF_MAIN_WIDTH = 504;
  DEF_MAIN_HEIGHT = 303;
  DEF_MAIN_MIN_WIDTH = 504;
  DEF_MAIN_MIN_HEIGHT = 303;

  { ═══════════════════════════════════════════════════════════════════════════
    UI COLORS
    ═══════════════════════════════════════════════════════════════════════════ }
  COLOR_PANEL = TColor($2D2D2D);

  { ═══════════════════════════════════════════════════════════════════════════
    TIMER INTERVALS (milliseconds)
    ═══════════════════════════════════════════════════════════════════════════ }
  TIMER_POSITION_UPDATE = 100;

  { ═══════════════════════════════════════════════════════════════════════════
    PLAYLIST SETTINGS
    ═══════════════════════════════════════════════════════════════════════════ }
  MAX_RECENT_FILES = 20;
  MAX_HISTORY_ITEMS = 500;

  { ═══════════════════════════════════════════════════════════════════════════
    FILE FILTERS
    ═══════════════════════════════════════════════════════════════════════════ }
  FILTER_ALL_MEDIA = 'All Media Files|*.avi;*.mkv;*.mp4;*.m4v;*.mov;*.wmv;*.flv;' +
    '*.webm;*.mpeg;*.mpg;*.vob;*.ts;*.m2ts;*.divx;*.xvid;*.3gp;*.ogv;*.rmvb;' +
    '*.mp3;*.flac;*.ogg;*.opus;*.m4a;*.aac;*.wma;*.wav;*.ape;*.mpc;*.mka;' +
    '*.m3u;*.m3u8;*.pls;*.cue|';

  FILTER_VIDEO = 'Video Files|*.avi;*.mkv;*.mp4;*.m4v;*.mov;*.wmv;*.flv;*.webm;' +
    '*.mpeg;*.mpg;*.vob;*.ts;*.m2ts;*.divx;*.xvid;*.3gp;*.ogv;*.rmvb|';

  FILTER_AUDIO = 'Audio Files|*.mp3;*.flac;*.ogg;*.opus;*.m4a;*.aac;*.wma;' +
    '*.wav;*.ape;*.mpc;*.mka|';

  FILTER_PLAYLIST = 'Playlist Files|*.m3u;*.m3u8;*.pls;*.xspf;*.cue|';

  FILTER_SUBTITLE = 'Subtitle Files|*.srt;*.ass;*.ssa;*.sub;*.idx;*.vtt;*.sup|';

  FILTER_ALL = 'All Files|*.*';

  { Combined filters for open dialogs }
  DIALOG_FILTER_MEDIA = FILTER_ALL_MEDIA + FILTER_VIDEO + FILTER_AUDIO +
    FILTER_PLAYLIST + FILTER_ALL;

  DIALOG_FILTER_SUBTITLE = FILTER_SUBTITLE + FILTER_ALL;

  { ═══════════════════════════════════════════════════════════════════════════
    CONFIG SECTIONS
    ═══════════════════════════════════════════════════════════════════════════ }
  INI_SECTION_GENERAL = 'General';
  INI_SECTION_VIDEO = 'Video';
  INI_SECTION_AUDIO = 'Audio';
  INI_SECTION_SUBTITLES = 'Subtitles';
  INI_SECTION_CACHE = 'Cache';
  INI_SECTION_PLAYLIST = 'Playlist';
  INI_SECTION_EQUALIZER = 'Equalizer';
  INI_SECTION_HISTORY = 'History';

implementation

end.
